const doctors = [
  { id: 1, name: "Dr. John Smith", specialty: "Cardiology" },
  { id: 2, name: "Dr. Sarah Johnson", specialty: "Dermatology" },
  { id: 3, name: "Dr. Michael Davis", specialty: "Orthopedics" },
  { id: 4, name: "Dr. Emily White", specialty: "Pediatrics" },
  { id: 5, name: "Dr. Robert Wilson", specialty: "Neurology" },
  { id: 6, name: "Dr. Jessica Taylor", specialty: "Gastroenterology" },
  { id: 7, name: "Dr. Brian Miller", specialty: "Ophthalmology" },
  { id: 8, name: "Dr. Olivia Brown", specialty: "Rheumatology" },
  { id: 9, name: "Dr. Christopher Lee", specialty: "Cardiac Surgery" },
  { id: 10, name: "Dr. Amanda Martinez", specialty: "Endocrinology" },
  { id: 11, name: "Dr. Matthew Anderson", specialty: "Urology" },
  { id: 12, name: "Dr. Laura Garcia", specialty: "Hematology" },
  { id: 13, name: "Dr. Kevin Robinson", specialty: "Pulmonology" },
  { id: 14, name: "Dr. Natalie Clark", specialty: "Oncology" },
  { id: 15, name: "Dr. Anthony Carter", specialty: "Nephrology" },
  { id: 16, name: "Dr. Megan Baker", specialty: "Gynecology" },
  { id: 17, name: "Dr. Benjamin Hill", specialty: "Allergy and Immunology" },
  { id: 18, name: "Dr. Rachel Turner", specialty: "Infectious Disease" },
  { id: 19, name: "Dr. Daniel Reed", specialty: "Psychiatry" },
  { id: 20, name: "Dr. Kimberly Adams", specialty: "Rheumatology" },
  { id: 21, name: "Dr. Jonathan White", specialty: "Neurology" },
  { id: 22, name: "Dr. Jennifer Lewis", specialty: "Dermatology" },
  { id: 23, name: "Dr. William Clark", specialty: "Orthopedics" },
  { id: 24, name: "Dr. Sophia Rodriguez", specialty: "Pediatrics" },
  { id: 25, name: "Dr. David Wilson", specialty: "Cardiology" },
  { id: 26, name: "Dr. Lauren Moore", specialty: "Endocrinology" },
  { id: 27, name: "Dr. Eric Taylor", specialty: "Ophthalmology" },
  { id: 28, name: "Dr. Amber Davis", specialty: "Gastroenterology" },
  { id: 29, name: "Dr. Ryan Garcia", specialty: "Cardiac Surgery" },
  { id: 30, name: "Dr. Madison Miller", specialty: "Urology" },
  { id: 31, name: "Dr. Nathan Smith", specialty: "Hematology" },
  { id: 32, name: "Dr. Emma Martinez", specialty: "Pulmonology" },
  { id: 33, name: "Dr. Jacob Turner", specialty: "Oncology" },
  { id: 34, name: "Dr. Chloe Baker", specialty: "Nephrology" },
  { id: 35, name: "Dr. Andrew Hill", specialty: "Gynecology" },
  { id: 36, name: "Dr. Victoria Reed", specialty: "Allergy and Immunology" },
  { id: 37, name: "Dr. Ethan Adams", specialty: "Infectious Disease" },
  { id: 38, name: "Dr. Lily White", specialty: "Psychiatry" },
  { id: 39, name: "Dr. Isaac Robinson", specialty: "Rheumatology" },
  { id: 40, name: "Dr. Ava Turner", specialty: "Neurology" },
  { id: 41, name: "Dr. Carter Lewis", specialty: "Dermatology" },
  { id: 42, name: "Dr. Zoe Clark", specialty: "Orthopedics" },
  { id: 43, name: "Dr. Tyler Rodriguez", specialty: "Pediatrics" },
  { id: 44, name: "Dr. Mia Wilson", specialty: "Cardiology" },
  { id: 45, name: "Dr. Evan Moore", specialty: "Endocrinology" },
  { id: 46, name: "Dr. Lily Taylor", specialty: "Ophthalmology" },
  { id: 47, name: "Dr. Noah Davis", specialty: "Gastroenterology" },
  { id: 48, name: "Dr. Addison Garcia", specialty: "Cardiac Surgery" },
  { id: 49, name: "Dr. Elijah Miller", specialty: "Urology" },
  { id: 50, name: "Dr. Grace Smith", specialty: "Hematology" },
  { id: 51, name: "Dr. Jackson Martinez", specialty: "Pulmonology" },
  { id: 52, name: "Dr. Sophia Turner", specialty: "Oncology" },
  { id: 53, name: "Dr. Samuel Baker", specialty: "Nephrology" },
  { id: 54, name: "Dr. Aria Hill", specialty: "Gynecology" },
  { id: 55, name: "Dr. Brayden Reed", specialty: "Allergy and Immunology" },
  { id: 56, name: "Dr. Clara Adams", specialty: "Infectious Disease" },
  { id: 57, name: "Dr. Luke White", specialty: "Psychiatry" },
  { id: 58, name: "Dr. Nora Robinson", specialty: "Rheumatology" },
  { id: 59, name: "Dr. Leo Turner", specialty: "Neurology" },
  { id: 60, name: "Dr. Stella Lewis", specialty: "Dermatology" },
  { id: 61, name: "Dr. Gabriel Clark", specialty: "Orthopedics" },
  { id: 62, name: "Dr. Ruby Rodriguez", specialty: "Pediatrics" },
  { id: 63, name: "Dr. Caleb Wilson", specialty: "Cardiology" },
  { id: 64, name: "Dr. Isabella Moore", specialty: "Endocrinology" },
  { id: 65, name: "Dr. Levi Taylor", specialty: "Ophthalmology" },
];

export default doctors;
