const doctors = [
  { name: "Dr. John Smith", specialty: "Cardiology" },
  { name: "Dr. Sarah Johnson", specialty: "Dermatology" },
  { name: "Dr. Michael Davis", specialty: "Orthopedics" },
  { name: "Dr. Emily White", specialty: "Pediatrics" },
  { name: "Dr. Robert Wilson", specialty: "Neurology" },
  { name: "Dr. Jessica Taylor", specialty: "Gastroenterology" },
  { name: "Dr. Brian Miller", specialty: "Ophthalmology" },
  { name: "Dr. Olivia Brown", specialty: "Rheumatology" },
  { name: "Dr. Christopher Lee", specialty: "Cardiac Surgery" },
  { name: "Dr. Amanda Martinez", specialty: "Endocrinology" },
  { name: "Dr. Matthew Anderson", specialty: "Urology" },
  { name: "Dr. Laura Garcia", specialty: "Hematology" },
  { name: "Dr. Kevin Robinson", specialty: "Pulmonology" },
  { name: "Dr. Natalie Clark", specialty: "Oncology" },
  { name: "Dr. Anthony Carter", specialty: "Nephrology" },
  { name: "Dr. Megan Baker", specialty: "Gynecology" },
  { name: "Dr. Benjamin Hill", specialty: "Allergy and Immunology" },
  { name: "Dr. Rachel Turner", specialty: "Infectious Disease" },
  { name: "Dr. Daniel Reed", specialty: "Psychiatry" },
  { name: "Dr. Kimberly Adams", specialty: "Rheumatology" },
  { name: "Dr. Jonathan White", specialty: "Neurology" },
  { name: "Dr. Jennifer Lewis", specialty: "Dermatology" },
  { name: "Dr. William Clark", specialty: "Orthopedics" },
  { name: "Dr. Sophia Rodriguez", specialty: "Pediatrics" },
  { name: "Dr. David Wilson", specialty: "Cardiology" },
  { name: "Dr. Lauren Moore", specialty: "Endocrinology" },
  { name: "Dr. Eric Taylor", specialty: "Ophthalmology" },
  { name: "Dr. Amber Davis", specialty: "Gastroenterology" },
  { name: "Dr. Ryan Garcia", specialty: "Cardiac Surgery" },
  { name: "Dr. Madison Miller", specialty: "Urology" },
  { name: "Dr. Nathan Smith", specialty: "Hematology" },
  { name: "Dr. Emma Martinez", specialty: "Pulmonology" },
  { name: "Dr. Jacob Turner", specialty: "Oncology" },
  { name: "Dr. Chloe Baker", specialty: "Nephrology" },
  { name: "Dr. Andrew Hill", specialty: "Gynecology" },
  { name: "Dr. Victoria Reed", specialty: "Allergy and Immunology" },
  { name: "Dr. Ethan Adams", specialty: "Infectious Disease" },
  { name: "Dr. Lily White", specialty: "Psychiatry" },
  { name: "Dr. Isaac Robinson", specialty: "Rheumatology" },
  { name: "Dr. Ava Turner", specialty: "Neurology" },
  { name: "Dr. Carter Lewis", specialty: "Dermatology" },
  { name: "Dr. Zoe Clark", specialty: "Orthopedics" },
  { name: "Dr. Tyler Rodriguez", specialty: "Pediatrics" },
  { name: "Dr. Mia Wilson", specialty: "Cardiology" },
  { name: "Dr. Evan Moore", specialty: "Endocrinology" },
  { name: "Dr. Lily Taylor", specialty: "Ophthalmology" },
  { name: "Dr. Noah Davis", specialty: "Gastroenterology" },
  { name: "Dr. Addison Garcia", specialty: "Cardiac Surgery" },
  { name: "Dr. Elijah Miller", specialty: "Urology" },
  { name: "Dr. Grace Smith", specialty: "Hematology" },
  { name: "Dr. Jackson Martinez", specialty: "Pulmonology" },
  { name: "Dr. Sophia Turner", specialty: "Oncology" },
  { name: "Dr. Samuel Baker", specialty: "Nephrology" },
  { name: "Dr. Aria Hill", specialty: "Gynecology" },
  { name: "Dr. Brayden Reed", specialty: "Allergy and Immunology" },
  { name: "Dr. Clara Adams", specialty: "Infectious Disease" },
  { name: "Dr. Luke White", specialty: "Psychiatry" },
  { name: "Dr. Nora Robinson", specialty: "Rheumatology" },
  { name: "Dr. Leo Turner", specialty: "Neurology" },
  { name: "Dr. Stella Lewis", specialty: "Dermatology" },
  { name: "Dr. Gabriel Clark", specialty: "Orthopedics" },
  { name: "Dr. Ruby Rodriguez", specialty: "Pediatrics" },
  { name: "Dr. Caleb Wilson", specialty: "Cardiology" },
  { name: "Dr. Isabella Moore", specialty: "Endocrinology" },
  { name: "Dr. Levi Taylor", specialty: "Ophthalmology" },
  { name: "Dr. Zoe Davis", specialty: "Gastroenterology" },
  { name: "Dr. Eli Garcia", specialty: "Cardiac Surgery" },
  { name: "Dr. Scarlett Miller", specialty: "Urology" },
  { name: "Dr. Mason Smith", specialty: "Hematology" },
  { name: "Dr. Isla Martinez", specialty: "Pulmonology" },
  { name: "Dr. Anthony Turner", specialty: "Oncology" },
  { name: "Dr. Savannah Baker", specialty: "Nephrology" },
  { name: "Dr. Hayden Hill", specialty: "Gynecology" },
  { name: "Dr. Zoe Reed", specialty: "Allergy and Immunology" },
  { name: "Dr. Max Adams", specialty: "Infectious Disease" },
  { name: "Dr. Lucy White", specialty: "Psychiatry" },
  { name: "Dr. Eli Robinson", specialty: "Rheumatology" },
  { name: "Dr. Bella Turner", specialty: "Neurology" },
  { name: "Dr. Wyatt Lewis", specialty: "Dermatology" },
  { name: "Dr. Eva Clark", specialty: "Orthopedics" },
  { name: "Dr. Owen Rodriguez", specialty: "Pediatrics" },
  { name: "Dr. Zoey Wilson", specialty: "Cardiology" },
  { name: "Dr. Jackson Moore", specialty: "Endocrinology" },
  { name: "Dr. Hazel Taylor", specialty: "Ophthalmology" },
  { name: "Dr. Miles Davis", specialty: "Gastroenterology" },
  { name: "Dr. Penelope Garcia", specialty: "Cardiac Surgery" },
  { name: "Dr. Liam Miller", specialty: "Urology" },
  { name: "Dr. Violet Smith", specialty: "Hematology" },
  { name: "Dr. Caleb Martinez", specialty: "Pulmonology" },
  { name: "Dr. Stella Turner", specialty: "Oncology" },
  { name: "Dr. Samuel Baker", specialty: "Nephrology" },
  { name: "Dr. Aria Hill", specialty: "Gynecology" },
  { name: "Dr. Brayden Reed", specialty: "Allergy and Immunology" },
  { name: "Dr. Clara Adams", specialty: "Infectious Disease" },
  { name: "Dr. Luke White", specialty: "Psychiatry" },
  { name: "Dr. Nora Robinson", specialty: "Rheumatology" },
  { name: "Dr. Leo Turner", specialty: "Neurology" },
  { name: "Dr. Stella Lewis", specialty: "Dermatology" },
  { name: "Dr. Gabriel Clark", specialty: "Orthopedics" },
  { name: "Dr. Ruby Rodriguez", specialty: "Pediatrics" },
  { name: "Dr. Caleb Wilson", specialty: "Cardiology" },
  { name: "Dr. Isabella Moore", specialty: "Endocrinology" },
  { name: "Dr. Levi Taylor", specialty: "Ophthalmology" },
  { name: "Dr. Zoe Davis", specialty: "Gastroenterology" },
  { name: "Dr. Eli Garcia", specialty: "Cardiac Surgery" },
  { name: "Dr. Scarlett Miller", specialty: "Urology" },
  { name: "Dr. Mason Smith", specialty: "Hematology" },
  { name: "Dr. Isla Martinez", specialty: "Pulmonology" },
  { name: "Dr. Anthony Turner", specialty: "Oncology" },
  { name: "Dr. Savannah Baker", specialty: "Nephrology" },
  { name: "Dr. Hayden Hill", specialty: "Gynecology" },
  { name: "Dr. Zoe Reed", specialty: "Allergy and Immunology" },
  { name: "Dr. Max Adams", specialty: "Infectious Disease" },
  { name: "Dr. Lucy White", specialty: "Psychiatry" },
  { name: "Dr. Eli Robinson", specialty: "Rheumatology" },
  { name: "Dr. Bella Turner", specialty: "Neurology" },
  { name: "Dr. Wyatt Lewis", specialty: "Dermatology" },
  { name: "Dr. Eva Clark", specialty: "Orthopedics" },
  { name: "Dr. Owen Rodriguez", specialty: "Pediatrics" },
  { name: "Dr. Zoey Wilson", specialty: "Cardiology" },
  { name: "Dr. Jackson Moore", specialty: "Endocrinology" },
  { name: "Dr. Hazel Taylor", specialty: "Ophthalmology" },
  { name: "Dr. Miles Davis", specialty: "Gastroenterology" },
  { name: "Dr. Penelope Garcia", specialty: "Cardiac Surgery" },
  { name: "Dr. Liam Miller", specialty: "Urology" },
  { name: "Dr. Violet Smith", specialty: "Hematology" },
  { name: "Dr. Caleb Martinez", specialty: "Pulmonology" },
  { name: "Dr. Stella Turner", specialty: "Oncology" },
  { name: "Dr. Samuel Baker", specialty: "Nephrology" },
  { name: "Dr. Aria Hill", specialty: "Gynecology" },
  { name: "Dr. Brayden Reed", specialty: "Allergy and Immunology" },
  { name: "Dr. Clara Adams", specialty: "Infectious Disease" },
  { name: "Dr. Luke White", specialty: "Psychiatry" },
  { name: "Dr. Nora Robinson", specialty: "Rheumatology" },
  { name: "Dr. Leo Turner", specialty: "Neurology" },
  { name: "Dr. Stella Lewis", specialty: "Dermatology" },
  { name: "Dr. Gabriel Clark", specialty: "Orthopedics" },
  { name: "Dr. Ruby Rodriguez", specialty: "Pediatrics" },
  { name: "Dr. Caleb Wilson", specialty: "Cardiology" },
  { name: "Dr. Isabella Moore", specialty: "Endocrinology" },
  { name: "Dr. Levi Taylor", specialty: "Ophthalmology" },
  { name: "Dr. Zoe Davis", specialty: "Gastroenterology" },
  { name: "Dr. Eli Garcia", specialty: "Cardiac Surgery" },
  { name: "Dr. Scarlett Miller", specialty: "Urology" },
  { name: "Dr. Mason Smith", specialty: "Hematology" },
  { name: "Dr. Isla Martinez", specialty: "Pulmonology" },
  { name: "Dr. Anthony Turner", specialty: "Oncology" },
  { name: "Dr. Savannah Baker", specialty: "Nephrology" },
  { name: "Dr. Hayden Hill", specialty: "Gynecology" },
  { name: "Dr. Zoe Reed", specialty: "Allergy and Immunology" },
  { name: "Dr. Max Adams", specialty: "Infectious Disease" },
  { name: "Dr. Lucy White", specialty: "Psychiatry" },
  { name: "Dr. Eli Robinson", specialty: "Rheumatology" },
  { name: "Dr. Bella Turner", specialty: "Neurology" },
  { name: "Dr. Wyatt Lewis", specialty: "Dermatology" },
  { name: "Dr. Eva Clark", specialty: "Orthopedics" },
  { name: "Dr. Owen Rodriguez", specialty: "Pediatrics" },
  { name: "Dr. Zoey Wilson", specialty: "Cardiology" },
  { name: "Dr. Jackson Moore", specialty: "Endocrinology" },
  { name: "Dr. Hazel Taylor", specialty: "Ophthalmology" },
  { name: "Dr. Miles Davis", specialty: "Gastroenterology" },
  { name: "Dr. Penelope Garcia", specialty: "Cardiac Surgery" },
  { name: "Dr. Liam Miller", specialty: "Urology" },
  { name: "Dr. Violet Smith", specialty: "Hematology" },
  { name: "Dr. Caleb Martinez", specialty: "Pulmonology" },
  { name: "Dr. Stella Turner", specialty: "Oncology" },
];

export default doctors;
